name: Agent Diaries
title: Keeping track of everything
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about what hermes does"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://coetzeer.github.io'
baseurl:        '/jekyll-theme-kactus'
author:         'Your Name'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year-:month-:day/:title/
future:          true


defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
